<?php

/**
 * IDE helper stubs for the jsonPaginate macro.
 *
 * This file provides autocompletion support for IDEs like PhpStorm and VSCode.
 * Do not edit this file manually - it is maintained by the package authors.
 *
 * @see https://github.com/spatie/laravel-json-api-paginate
 */

namespace Illuminate\Database\Eloquent {

    use Illuminate\Contracts\Pagination\CursorPaginator;
    use Illuminate\Contracts\Pagination\LengthAwarePaginator;
    use Illuminate\Contracts\Pagination\Paginator;

    /**
     * @method LengthAwarePaginator|Paginator|CursorPaginator jsonPaginate(?int $maxResults = null, ?int $defaultSize = null, ?int $totalResults = null)
     */
    class Builder
    {
        //
    }
}

namespace Illuminate\Database\Query {

    use Illuminate\Contracts\Pagination\CursorPaginator;
    use Illuminate\Contracts\Pagination\LengthAwarePaginator;
    use Illuminate\Contracts\Pagination\Paginator;

    /**
     * @method LengthAwarePaginator|Paginator|CursorPaginator jsonPaginate(?int $maxResults = null, ?int $defaultSize = null, ?int $totalResults = null)
     */
    class Builder
    {
        //
    }
}

namespace Illuminate\Database\Eloquent\Relations {

    use Illuminate\Contracts\Pagination\CursorPaginator;
    use Illuminate\Contracts\Pagination\LengthAwarePaginator;
    use Illuminate\Contracts\Pagination\Paginator;

    /**
     * @method LengthAwarePaginator|Paginator|CursorPaginator jsonPaginate(?int $maxResults = null, ?int $defaultSize = null, ?int $totalResults = null)
     */
    class BelongsToMany
    {
        //
    }

    /**
     * @method LengthAwarePaginator|Paginator|CursorPaginator jsonPaginate(?int $maxResults = null, ?int $defaultSize = null, ?int $totalResults = null)
     */
    class HasManyThrough
    {
        //
    }
}
